# Shiny Applications 

<br>

**R Shiny Applications are listed below. Click the links for more information!**

<br>

**lrd: Lexical Response Data**

*lrd* provides functions for automatically scoring lexical data from cued-recall and free-recall studies.

  + [Application](https://npm27.shinyapps.io/lrd_shiny/)
  + [Tutorial](https://www.macapsych.com/lexical-re)
  + [Paper](https://link.springer.com/article/10.3758/s13428-021-01718-y)

<br>

**Affordance Norms**

This shiny application provides a searchable portal for Maxwell et al.'s (2024) affordance norms. Affordance measures include AFS (Affordance Strength) and AFP (Affordance proportion), which reflect the probability of an object eliciting a specific affordance, and AFFS (Affordance set size), which denotes the total number of affordances eliicted per cue. In addition to affordance information, the shiny application also displays lexical properties for cue words, including frequency, concreteness, length, age-of-acquisition, body-object interaction, and animacy ratings

  + [Application](https://npm27.shinyapps.io/Affordance_Norms/)
  + [Paper](https://link.springer.com/article/10.3758/s13428-024-02486-1)
  